CL:
  MODEL:
    DEVICE: cuda
    NET: MLP
  OPTIM:
    LR: 0.001
    MOMENTUM: 0
    TYPE: sgd
DATA:
  IB:
    ALPHA: 1
  NAME: MNIST
  PATH: ./datasets
  SEED: 0
  TEST:
    BATCH: 512
    WORKERS: 0
  TRAIN:
    BATCH: 64
    WORKERS: 0
FL:
  ALG: FedAvg
  PARAM: None
  CLIENT:
    ACTIVE: 10
    TOTAL: 100
  EPOCH:
    GLOBAL: 20
    LOCAL: 2
  EVAL: 1
  CEVAL: 10
  LR: 1
  LOG: 30
  NAME:
  PROJECT: fedga
