CL:
  MODEL:
    NET: MLP
  OPTIM:
    LR: 0.001
    TYPE: adam
DATA:
  IB:
    ALPHA: 0.5
  NAME: MNIST
  PATH: ./datasets
  SEED: 0
FL:
  ALG: FedAvg
  PARAM: None
  EPOCH:
    GLOBAL: 150
  EVAL: 1
  CEVAL: 10
  LR: 1
  LOG: 30
