CL:
  MODEL:
    NET: LeNet
  OPTIM:
    LR: 0.03
    MOMENTUM: 0.9
    TYPE: sgd
DATA:
  IB:
    ALPHA: 0.5
  NAME: SVHN
  PATH: ./datasets
  SEED: 0
FL:
  ALG: FedAvg
  PARAM: None
  EPOCH:
    GLOBAL: 300
  EVAL: 1
  CEVAL: 10
  LR: 1
  LOG: 30
